tfaBot:
  # Required bot url
  # config:
  #   botUrl: https://url.to.google.sheet.conf
  config: {}

  # Docker image repository
  image: bedrocksolutions/tfa-bot

  # Docker image tag
  imageTag: latest

  # Docker image pull policy
  pullPolicy: Always

  # Container resource limits and requests
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 96Mi

deployment:
  replicas: 1
  restartPolicy: Always
